name: Analyze

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cloc cppcheck
      - name: Dependency Information
        run: |
          echo "cloc `cloc --version`"
          echo "`cppcheck --version`"
      - name: Run Analysis
        run: |
          make analyze
