name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev
      - name: Dependency Information
        run: |
          echo "gcc `gcc --version | grep gcc | awk '{print $3}'`"
          echo "sdl2 `sdl2-config --version`"
      - name: Run Unittests
        run: |
          make test
